steps:
  - uses: bhowell2/github-substring-action
    id: one
    with:
      value: ${issue.milestones.created_at}
      length_from_start: 10
autoCloseIssue: true
defaultBranch: ${steps.one.outputs.substring}
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
