autoCloseIssue: true
defaultBranch:
- uses: ajilraju/actions-date@v0.1
  with:
    args: date "+%d%m%Y"
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
