on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [ assigned ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show date
        run: echo $(date '+%d%m%Y')
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d%m%Y')"
      - uses: actions/checkout@v2
        with:
          ref: "master"
      - run: |
          git config --local user.email "github@organization.com"
          git config --local user.name "GitHub Actions"
      - run: |
          git checkout -b RC-${{ steps.todays-date.outputs.date }}
          git push --set-upstream origin \
            SPRINT-${{steps.date.output.date}}
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          autoCloseIssue: true
          defaultBranch: SPRINT-${{steps.date.output.date}}
          copyIssueDescriptionToPR: true
          copyIssueLabelsToPR: true
          copyIssueAssigneeToPR: true
