on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [ assigned ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show date
        run: echo $(date '+%d%m%Y')
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d%m%Y')"
      - name: Create Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branchName: S${{steps.date.output.date}}
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          autoCloseIssue: true
          prefix: S${{steps.date.output.date}}
          defaultBranch: S${{steps.date.output.date}}
          copyIssueDescriptionToPR: true
          copyIssueLabelsToPR: true
          copyIssueAssigneeToPR: true
